### PR TITLE
Support for namedParameters in cassandra-sink ingestQuery

### PR DESCRIPTION
**Pull request by ashu-walmart**
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by ashu-walmart** [comment]
Support for namedParameters in cassandra-sink ingestQuery

**Comment by ashu-walmart** [comment]
Fixes spring-cloud/spring-cloud-stream-modules#183

**Comment by artembilan** [comment]
@ashu-walmart ,

thank you for the contribution!
We'll come to you the next week for review.

Or... Let us know if that is immediate requirements for you.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-cloud/spring-cloud-stream-modules/commit/2700ed45ffecd3d6d5feff3230f6f96f3e0df999.

I spent already a lot of time to figure out if we can make Embedded Cassandra not so aggressive for resources, but looks like no choice and we will still have some sporadic failures on the matter.

The PR merged as is with the simple code style polishing.

Thank you, @ashu-walmart , for the contribution.
Looking forward for more!

**Pull request closed without merging**
