### PR TITLE
removing lombok from web socket sink and avoiding 9393 port conflict in test

### PR DESCRIPTION
**Pull request by markfisher**

### CODE REVIEW

**Comment by mbogoevici** [comment]
While we're at it, could we just rename this module altogether? While it is valuable to have Netty in, it feels like the default websocket implementation could be a much simpler approach.

**Comment by markfisher** [comment]
+1 for creating a new websocket sink altogether, and qualifying this one

**Comment by garyrussell** [comment]
LGTM, except I think it would be even better to use a random port for the test.

Polishing here for your approval b4 merging... https://github.com/garyrussell/spring-cloud-stream-modules/commit/66a562b3d67546cb338b245d5205f89256039784

**Comment by markfisher** [comment]
Yes, the random port is much better. Thanks!

**Comment by garyrussell** [comment]
rebased, merged as bb6f1bfc0aa5a938fa48faf3c3ebac1491e8c303

**Pull request closed without merging**
