### PR TITLE
Fix counter sink

### LINKED ISSUE #248: Counter sink doesn't work
As a user, I'm trying to use the `counter` sink and I'm unable to see the counts aggregated in redis store. 

[_note: it was recently changed to have `redis` as the default store (through: #230) for all the counters_]

**stream:**
```
dataflow:>stream create foodfdsfsdfsdsfgdfg --definition "time | counter" --deploy
```
also tried.. 
```
dataflow:>stream create foodfdsfsdfsdsfgdfg --definition "time | counter --store=redis" --deploy
```

**counter list:**
```
dataflow:>counter list
╔════════════╗
║Counter name║
╚════════════╝
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Fix logic that creates RedisMetricRepository
  - Add test to assert redis metric repository

This resolves #248

### CODE REVIEW

**Comment by garyrussell** [comment]
Hehe just noticed this - I found this problem when I ported the sink to starters this morning; I fixed it in a similar manner.

**Comment by sabbyanandan** [comment]
@garyrussell: Is this already addressed with the move or we would need this PR ported over, too?

**Comment by sabbyanandan** [comment]
Never mind; I see this is already addressed in the app-starter repo. @ilayaperumalg: perhaps we could still port over the test contributions.

**Comment by ilayaperumalg** [comment]
@sabbyanandan Sure, will close this PR once the test changes are ported to app starters repo.

**Comment by sabbyanandan** [comment]
This work is already complete.

**Pull request closed without merging**
